/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Was ist zu sehen? Pflicht für Bilder, für Videos nicht nötig.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * Urheberin oder Quelle, falls ein Nachweis nötig ist.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Teil der URL. Leer lassen, um ihn aus dem Titel abzuleiten.
   */
  slug: string;
  layout: (
    | HeroBlock
    | PageHeaderBlock
    | TextIntroBlock
    | PillarCardsBlock
    | DayTimelineBlock
    | QuoteBlock
    | CtaBannerBlock
    | TimetableBlock
    | HolidayPlanBlock
  )[];
  meta?: {
    /**
     * Leer lassen, um den Seitentitel zu verwenden.
     */
    title?: string | null;
    /**
     * Höchstens 160 Zeichen.
     */
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Kleine Zeile über dem Titel, üblicherweise Schultyp, Ort und Kanton.
   */
  kicker?: string | null;
  heading: string;
  /**
   * Ein bis zwei Sätze. Wird auf 48 Zeichen Breite umbrochen.
   */
  lead?: string | null;
  /**
   * MP4 oder WebM, höchstens 3 MB. Läuft stumm und in Schleife.
   */
  video?: (number | null) | Media;
  /**
   * Standbild. Wird vor dem ersten Frame und bei reduzierter Bewegung gezeigt.
   */
  poster?: (number | null) | Media;
  /**
   * Sekunden Pause zwischen zwei Durchläufen.
   */
  loopPause?: number | null;
  accent: 'sage' | 'fir' | 'graphite';
  /**
   * Dünne Fortschrittslinie unter dem Teaser-Band.
   */
  showProgress?: boolean | null;
  /**
   * Nach dem ersten Durchlauf wird das Video weichgezeichnet, der Text tritt hervor.
   */
  softenAfter?: boolean | null;
  /**
   * Genau drei Teaser. Je Teaser höchstens rund 30 Zeichen pro Zeile.
   */
  teasers?:
    | {
        text: string;
        link: LinkField;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkField".
 */
export interface LinkField {
  type: 'internal' | 'external' | 'email';
  /**
   * Der sichtbare Linktext. Ohne Pfeil — den setzt das Layout.
   */
  label: string;
  page?: (number | null) | Page;
  /**
   * Vollständige Adresse inklusive https://
   */
  url?: string | null;
  email?: string | null;
  newTab?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock".
 */
export interface PageHeaderBlock {
  /**
   * Optionales, rein dekoratives Symbol über dem Titel — zum Beispiel das Signet der Schule. Es wird ohne Alternativtext ausgegeben, weil der Titel direkt darunter steht; für ein Bild mit eigener Aussage ist dieses Feld nicht gedacht. Ohne Bild beginnt die Seite direkt mit dem Titel.
   */
  icon?: (number | null) | Media;
  /**
   * Der Titel der Seite. Zeilenumbrüche werden übernommen — das Design bricht die Überschrift bewusst um.
   */
  heading: string;
  /**
   * Ein bis zwei Sätze neben dem Titel. Leer lassen für einen Titel allein.
   */
  lead?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHeader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextIntroBlock".
 */
export interface TextIntroBlock {
  /**
   * Zeilenumbrüche werden übernommen — das Design bricht die Überschrift bewusst um. Leer lassen für einen reinen Fliesstext-Abschnitt: der Text steht dann einspaltig und etwas grösser.
   */
  heading?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'textIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillarCardsBlock".
 */
export interface PillarCardsBlock {
  /**
   * Die Flächenfarbe ergibt sich aus der Position: 1. Karte Mint, 2. Karte Salbei, ab der 3. die Akzentfarbe.
   */
  cards?:
    | {
        /**
         * Zweistellig, z. B. 01.
         */
        index: string;
        /**
         * Ein Wort, z. B. Hof.
         */
        category: string;
        heading: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pillarCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DayTimelineBlock".
 */
export interface DayTimelineBlock {
  heading: string;
  entries?:
    | {
        /**
         * Format HH:MM, z. B. 07:30.
         */
        time: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dayTimeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  /**
   * Ohne Anführungszeichen erfassen — die setzt das Layout.
   */
  quote: string;
  /**
   * Wer hat es gesagt, z. B. Schulleitung.
   */
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock".
 */
export interface CtaBannerBlock {
  heading: string;
  /**
   * Kurzer Absatz, wird auf 52 Zeichen Breite umbrochen.
   */
  text?: string | null;
  link: LinkField;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimetableBlock".
 */
export interface TimetableBlock {
  heading: string;
  /**
   * Die Kopfzeile der Tabelle, üblicherweise Montag bis Freitag.
   */
  columns?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  rows?:
    | {
        /**
         * Inhalt der linken Kopfspalte, z. B. 08:15-09:00. Zeilenumbrüche werden übernommen. Leer lassen für eine Zeile ohne Zeitangabe.
         */
        time?: string | null;
        /**
         * Die Zellen werden wie in HTML von links nach rechts gefüllt. Eine Zelle, die von einem Zeilen- oder Spaltenverbund einer früheren Zelle bereits überdeckt ist, wird hier NICHT noch einmal erfasst.
         */
        cells?:
          | {
              /**
               * Leer lassen für eine leere Zelle. Zeilenumbrüche werden übernommen.
               */
              text?: string | null;
              colSpan?: number | null;
              rowSpan?: number | null;
              variant: 'lektion' | 'pause' | 'organisation';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auflösung der Abkürzungen unterhalb der Tabelle.
   */
  legend?:
    | {
        abbreviation: string;
        meaning: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timetable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HolidayPlanBlock".
 */
export interface HolidayPlanBlock {
  heading: string;
  years?:
    | {
        /**
         * Beispiel: Schulferien 2026 – 27.
         */
        label: string;
        entries?:
          | {
              /**
               * Beispiel: Herbstferien.
               */
              name: string;
              from: string;
              /**
               * Leer lassen für einen einzelnen freien Tag.
               */
              to?: string | null;
              /**
               * Kurzer Hinweis in Klammern, z. B. „7 Wochen“.
               */
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'holidayPlan';
}
/**
 * Veröffentlichte Events erscheinen automatisch auf der Seite „Events“, nach Datum sortiert.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Datum und Beginn. Ohne Uhrzeit (00:00) zeigt die Karte nur das Datum an.
   */
  date: string;
  /**
   * Wird auf der Eventkarte angezeigt.
   */
  image: number | Media;
  /**
   * Ein bis zwei Sätze. Leer lassen, wenn der Titel genügt.
   */
  description?: string | null;
  /**
   * Zum Beispiel: Schulhaus Unterbach.
   */
  location?: string | null;
  /**
   * Teil der URL. Leer lassen, um ihn aus dem Titel abzuleiten.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        pageHeader?: T | PageHeaderBlockSelect<T>;
        textIntro?: T | TextIntroBlockSelect<T>;
        pillarCards?: T | PillarCardsBlockSelect<T>;
        dayTimeline?: T | DayTimelineBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        timetable?: T | TimetableBlockSelect<T>;
        holidayPlan?: T | HolidayPlanBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  lead?: T;
  video?: T;
  poster?: T;
  loopPause?: T;
  accent?: T;
  showProgress?: T;
  softenAfter?: T;
  teasers?:
    | T
    | {
        text?: T;
        link?: T | LinkFieldSelect<T>;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkField_select".
 */
export interface LinkFieldSelect<T extends boolean = true> {
  type?: T;
  label?: T;
  page?: T;
  url?: T;
  email?: T;
  newTab?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock_select".
 */
export interface PageHeaderBlockSelect<T extends boolean = true> {
  icon?: T;
  heading?: T;
  lead?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextIntroBlock_select".
 */
export interface TextIntroBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillarCardsBlock_select".
 */
export interface PillarCardsBlockSelect<T extends boolean = true> {
  cards?:
    | T
    | {
        index?: T;
        category?: T;
        heading?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DayTimelineBlock_select".
 */
export interface DayTimelineBlockSelect<T extends boolean = true> {
  heading?: T;
  entries?:
    | T
    | {
        time?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock_select".
 */
export interface CtaBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  link?: T | LinkFieldSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimetableBlock_select".
 */
export interface TimetableBlockSelect<T extends boolean = true> {
  heading?: T;
  columns?:
    | T
    | {
        label?: T;
        id?: T;
      };
  rows?:
    | T
    | {
        time?: T;
        cells?:
          | T
          | {
              text?: T;
              colSpan?: T;
              rowSpan?: T;
              variant?: T;
              id?: T;
            };
        id?: T;
      };
  legend?:
    | T
    | {
        abbreviation?: T;
        meaning?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HolidayPlanBlock_select".
 */
export interface HolidayPlanBlockSelect<T extends boolean = true> {
  heading?: T;
  years?:
    | T
    | {
        label?: T;
        entries?:
          | T
          | {
              name?: T;
              from?: T;
              to?: T;
              note?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  image?: T;
  description?: T;
  location?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Name der Schule. Dient als Alternativtext des Logos und wird angezeigt, solange kein Logo hochgeladen ist.
   */
  wordmark: string;
  /**
   * Ohne Logo zeigt die Kopfzeile die Wortmarke als Text.
   */
  logo?: (number | null) | Media;
  /**
   * Beschriftung des Haus-Symbols links in der Navigation.
   */
  homeLabel: string;
  /**
   * Die Einträge der obersten Navigationszeile. Ein Klick klappt die Unterpunkte auf.
   */
  groups?:
    | {
        label: string;
        items?:
          | {
              link: LinkField;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Inhalt des Menüs hinter dem Symbol mit den drei Strichen.
   */
  utilityLinks?:
    | {
        link: LinkField;
        /**
         * Hebt den Eintrag in der Akzentfarbe hervor.
         */
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Blendet das Suchfeld rechts in der Navigation ein.
   */
  searchEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        /**
         * Zeilenumbruch mit Umschalt + Enter.
         */
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Strukturierte Angaben für Suchmaschinen (schema.org EducationalOrganization). Sie erscheinen nicht sichtbar auf der Seite.
   */
  organization: {
    name: string;
    streetAddress?: string | null;
    postalCode?: string | null;
    addressLocality?: string | null;
    /**
     * Kanton, z. B. BE.
     */
    addressRegion?: string | null;
    email?: string | null;
  };
  /**
   * Einzeilige Angabe ganz unten links.
   */
  legalNote?: string | null;
  legalLinks?:
    | {
        link: LinkField;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  wordmark?: T;
  logo?: T;
  homeLabel?: T;
  groups?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              link?: T | LinkFieldSelect<T>;
              id?: T;
            };
        id?: T;
      };
  utilityLinks?:
    | T
    | {
        link?: T | LinkFieldSelect<T>;
        highlight?: T;
        id?: T;
      };
  searchEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  organization?:
    | T
    | {
        name?: T;
        streetAddress?: T;
        postalCode?: T;
        addressLocality?: T;
        addressRegion?: T;
        email?: T;
      };
  legalNote?: T;
  legalLinks?:
    | T
    | {
        link?: T | LinkFieldSelect<T>;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}